API geolocalisation stored in articles
CraftAcademy/newsroom_api-april-2020 pull request #21
Opened 2020-06-02 12:14 UTC by PaulineBA

## [PT LINK]( https://www.pivotaltracker.com/story/show/173109448 )
### User Story
```
As a user
In order to read relevant articles close to my location
I would like to see relevant articles to be based on my location.
```

2020-06-02 12:20 UTC, oliverochman requested changes
Update seed file to have location as well

2020-06-02 12:20 UTC, oliverochman commented on spec/requests/api/admin/editor_can_add_location_spec.rb
> +RSpec.describe 'Api::Admin::Articles :update', type: :request do
fix indentation in this file

2020-06-02 12:28 UTC, erikbjoern requested changes
After you've made sure the old tests pass, this looks good!

2020-06-04 07:07 UTC, erikbjoern commented
This is being replaced with PR#22

2020-06-04 07:07 UTC, closed without merging